### ISSUE TITLE
Render model in Designer fails

### ISSUE THREAD

**Issue by shirokoweb** [awslabs/aws-refarch-wordpress#1]
When I try to render the [model](https://github.com/awslabs/aws-refarch-wordpress/blob/master/templates/aws-refarch-wordpress-master.yaml) in Designer it fails with following error message :

> Cannot render the template because of an error.: YAMLException: duplicated mapping key at line 292, column 32: Condition: DeployCloudFront ^

Lines 291-292 show :

```
    Condition: AvailableAWSRegion
    Condition: DeployCloudFront
```

I'm new to the syntax (first time ever using it) and I'm wondering which between these two is correct :

`Condition: [ AvailableAWSRegion, DeployCloudFront ]`

**or**
```
Condition:
- AvailableAWSRegion
- DeployCloudFront
```

Same question applies for lines 320-321 / 386-387

**Comment by darrylsosborne** [comment]
In cases like this where a top level condition is required I recommend adding an !And to the DeployElastiCache condition.

...
Conditions:
...  
  DeployElastiCache: !And
    - !Equals [ True, !Ref UseElastiCacheBoolean ]
    - !Condition AvailableAWSRegion

Resources:

...
  cloudfront:
    Condition: DeployCloudFront
...

Pushing out this fix to all affected sections of the master yml file within the next 24 hours.

**Comment by darrylsosborne** [comment]
Fix published and verified.

<img width="1018" alt="screen shot 2017-07-18 at 9 16 44 pm" src="https://user-images.githubusercontent.com/2607000/28347733-7b20398c-6bfe-11e7-9fc1-df264db0c281.png">
