### ISSUE TITLE
[ENHANCEMENT] Parameter to choose the version of wordpress

### ISSUE THREAD

**Issue by Orybon** [awslabs/aws-refarch-wordpress#11]
https://github.com/awslabs/aws-refarch-wordpress/blob/4cc5db2cb1d3fe038bfa949c47d6c06c2dca3519/templates/aws-refarch-wordpress-04-web.yaml#L583

Maybe in the next version add the [--version=<version>] option documented here : https://developer.wordpress.org/cli/commands/core/download/

It could be a great help to maintain environments.

**Comment by darrylsosborne** [comment]
Orybon,

Another great suggestion. Let me take a look at this over the next few days.

Thanks,

Darryl

**Comment by Orybon** [comment]
Thank you for taking into account this suggestion

**Comment by darrylsosborne** [comment]
Pushed 2.0.1 today (12/16/2017). It gives the ability to select the WordPress version, 4.5 and above. Possible versions: latest, nightly, 4.5, 4.6, 4.7, 4.8, 4.9. It will automatically download and install the latest minor version of the major version selected.
