### ISSUE TITLE
CloudFront Certificate ARN - Where can I find it? 

### ISSUE THREAD

**Issue by lfreneda** [awslabs/aws-refarch-wordpress#12]
Here can I find this information bellow:

![image](https://user-images.githubusercontent.com/372420/33955331-4af5301c-e022-11e7-8f7e-7f7edf8a6fc4.png)

![image](https://user-images.githubusercontent.com/372420/33955372-75201136-e022-11e7-9c94-64c87bfa00e5.png)

Thanks :(

**Comment by RGuilfoyle** [comment]
Configuring your site to be accessed over TLS/SSL is recommended, but optional, A certificate is required if you are configuring your site for secure access. The ARN of a certificate can be found in the Amazon Certificate Manager console if the cert was issued by ACM, or in IAM.  See the docs;
http://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_server-certs.html 
and
http://docs.aws.amazon.com/acm/latest/userguide/gs-acm-manage.html
I recommend, that you use Amazon Certificate Manager to issue a certificate for CloudFront, and/or for your Application Load Balancer. 
To use an ACM Certificate with Amazon CloudFront, you must request or import the certificate in the US East (N. Virginia) region.

The certificate with have an Amazon Resource Name (ARN) similar to this;
arn:aws:acm:us-east-1:123456789012:certificate/12345678-1234-1234-1234-123456789012

**Comment by lfreneda** [comment]
@RGuilfoyle Thanks, I will follow your instructions
