### ISSUE TITLE
Fail to create Stack

### ISSUE THREAD

**Issue by shirokoweb** [awslabs/aws-refarch-wordpress#2]
Despite several attempts, I'm unable to deploy the stack.
Here is the output that leads to a rollback :

> 11:37:04 UTC+0200 | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack | TestDom | The following resource(s) failed to create: [publicalb, efs, rds, bastion, elasticache]. . Rollback requested by user.
> -- | -- | -- | -- | --
>   | Physical ID:arn:aws:cloudformation:us-east-1:560474847061:stack/TestDom/9ab57870-6ad2-11e7-84fb-503aca2616d1
>   | Client Request Token:Console-CreateStack-8372e6ab-fe26-4512-a6fd-5027b2a18a33
>   | 11:37:02 UTC+0200 | CREATE_FAILED | AWS::CloudFormation::Stack | bastion | Resource creation cancelled
>   | Physical ID:arn:aws:cloudformation:us-east-1:560474847061:stack/TestDom-bastion-1ACPD1KWG5K7/41cf0720-6ad3-11e7-be2a-500c28b4e461
>   | Client Request Token:Console-CreateStack-8372e6ab-fe26-4512-a6fd-5027b2a18a33
>   | 11:37:02 UTC+0200 | CREATE_FAILED | AWS::CloudFormation::Stack | elasticache | Resource creation cancelled
>   | Physical ID:arn:aws:cloudformation:us-east-1:560474847061:stack/TestDom-elasticache-15WXD68ALIO17/41721a10-6ad3-11e7-a1fc-500c289032fe
>   | Client Request Token:Console-CreateStack-8372e6ab-fe26-4512-a6fd-5027b2a18a33
>   | 11:37:02 UTC+0200 | CREATE_FAILED | AWS::CloudFormation::Stack | publicalb | Resource creation cancelled
>   | Physical ID:arn:aws:cloudformation:us-east-1:560474847061:stack/TestDom-publicalb-12T7R99A3XTRZ/41dc9bb0-6ad3-11e7-9f7c-503aca261629
>   | Client Request Token:Console-CreateStack-8372e6ab-fe26-4512-a6fd-5027b2a18a33
>   | 11:37:02 UTC+0200 | CREATE_FAILED | AWS::CloudFormation::Stack | efs | Resource creation cancelled
>   | Physical ID:arn:aws:cloudformation:us-east-1:560474847061:stack/TestDom-efs-FOUIV7P1YWCS/421537e0-6ad3-11e7-805a-50d5ca6e604a
>   | Client Request Token:Console-CreateStack-8372e6ab-fe26-4512-a6fd-5027b2a18a33
>   | 11:37:01 UTC+0200 | CREATE_FAILED | AWS::CloudFormation::Stack | rds | Embedded stack arn:aws:cloudformation:us-east-1:560474847061:stack/TestDom-rds-1P8GDUYQ491N7/41c89e80-6ad3-11e7-85c4-5044763dbb7b was not successfully created: The following resource(s) failed to create: [DatabaseInstance1].
>   | Physical ID:arn:aws:cloudformation:us-east-1:560474847061:stack/TestDom-rds-1P8GDUYQ491N7/41c89e80-6ad3-11e7-85c4-5044763dbb7b
>   | Client Request Token:Console-CreateStack-8372e6ab-fe26-4512-a6fd-5027b2a18a33
>

**Comment by shirokoweb** [comment]
Little improvement
The RDS template fails because of DeletionPolicy.
After adding :
```
  DatabaseInstance1:
    Type: AWS::RDS::DBInstance
    **DeletionPolicy: Delete**
```
and
```
  DatabaseInstance0:
    Type: AWS::RDS::DBInstance
    **DeletionPolicy: Delete**
```
Helped solve create RDS stack

**Comment by darrylsosborne** [comment]
This is a known issue and has been recently reported by other customers as well. The Amazon RDS service team is currently working on the fix for this but there is no ETA as to when that would be pushed.

The work-around in the meanwhile is to specify a DeletionPolicy inside the DB instance resource definition that is failing to create, with the value of 'Delete'.  I will be pushing out a fix to this within the next 24 hours.

**Comment by darrylsosborne** [comment]
Fix published and verified.

<img width="1035" alt="screen shot 2017-07-18 at 9 58 23 pm" src="https://user-images.githubusercontent.com/2607000/28348777-7190980c-6c04-11e7-82db-58f31741cda1.png">
