### ISSUE TITLE
[Request] PHP5 rather than PHP7

### ISSUE THREAD

**Issue by Seblat5ch** [awslabs/aws-refarch-wordpress#3]
More of a [Feature Request] than an Issue. 

Our Website is not compatible with our existing site. therefore a request to choose different versions of PHP in my case version PHP5.6

**Comment by gshan05** [comment]
It will be great if we can have option to choose PHP5.6 version as our existing wordpress site is not php7 ready...thanks

**Comment by darrylsosborne** [comment]
Selecting PHP 5.5, 5.6, or 7.0 is now a parameter in version 2.0.0.
