### ISSUE TITLE
[Feature Consideration] Bastion Instance Type Configuration

### ISSUE THREAD

**Issue by michael-newman** [awslabs/aws-refarch-wordpress#8]
Feature Consideration:

For your consideration, you may want to you expose the Bastion Instance Type as a configuration element before the user runs the CloudFront Template (currently, it just defaults to t2.large within the Yaml file).

I realized it had a large server after the Templates ran. I changed it via making a copy of the Launch Configuration and reassigning the revised configuration to the ASG; but, thought it would be a nice extension to your comprehensive Template.

**Comment by darrylsosborne** [comment]
Mike, Thanks for the suggestion. I'll be pushing out a new version in the next few days and I'll be adding this to the template.
- Darryl

**Comment by jimmyjuarez** [comment]
@darrylsosborne I can use this feature too, really looking forward to the next release!  @RGuilfoyle, offered some great suggestions for me to learn how to use the bastion host.  When should we expext the next push?

**Comment by darrylsosborne** [comment]
Jimmy.  I'm testing version 2 over the weekend so we should have it pushed by Tuesday. 

    On Saturday, December 9, 2017 3:31 PM, Jimmy Juarez <notifications@github.com> wrote:
 

 @darrylsosborne I can use this feature too, really looking forward to the next release! @RGuilfoyle, offered some great suggestions for me to learn how to use the bastion host. When should we expext the next push?—

**Comment by darrylsosborne** [comment]
Bastion instance type selection is now a parameter in version 2.0.0
